#:schema node_modules/wrangler/config-schema.json
name = "worker"
main = "src/index.ts"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "STATE_KV"
id = "STATE_KV"
